### ISSUE TITLE
Change the CSV converter to keep the output same name as the input file

### ISSUE THREAD

**Issue by caljay98** [gopher-motorsports/DLM_data_parser#2]
Right now the csv converter requires an input and an output file. Change this so the output file is just "input_file.gdat.csv". Look at the ld converter as that is how that program works

**Comment by pyagnik1** [comment]
Hi 👋 @caljay98 can I fix this issue? I need to contribute to an open source project for my class. Thanks

**Comment by caljay98** [comment]
You can absolutely contribute! I will look over your PR sometime tomorrow. Thanks for pitching in!
